#kits_config.py

# Estructura: ID_DEL_KIT: [Lista de IDs de productos que lo componen]
KITS_ESTRUCTURA = {
    21657: [18547, 18548, 20093],
    21658: [20170, 18550, 19415],
    21656: [19415, 20093, 19653],
    21653: [19415, 20224],
    21655: [19415, 18921, 19187],
    22251: [22151, 20093, 20170],
    22005: [19415, 20170, 18550],
    22441: [22012, 19676, 19749],
    22619 : [19415,21670],
    22618 : [19415, 22285, 22151]   }

KITS_SHOPIFY = {
    "Kit Trío Serums +" : ["Serum C+ | Vitamina C","SERUM NZ | Niacinamida","SERUM H | Ultra Hydra B5"],
    "Rutina Antiage":["CREMA ANTIAGE NOCHE","CREMA ANTIAGE DIA","SERUM H | Ultra Hydra B5","ESPUMA DE LIMPIEZA FACIAL","AGUA TERMAL VOLCANICA"],
    "RUTINA ANTIEDAD":["CREMA ANTIAGE NOCHE","CREMA ANTIAGE DIA","SERUM H | Ultra Hydra B5","ESPUMA DE LIMPIEZA FACIAL","AGUA TERMAL VOLCANICA"],
    "RUTINA HIDRATANTE":["AGUA MICELAR 180","GEL HIDRATANTE | Hidratermal","AGUA TERMAL VOLCANICA","SERUM H | Ultra Hydra B5"],
    "RUTINA PIEL GRASA":["ESPUMA DE LIMPIEZA FACIAL","AGUA MICELAR 180","AGUA TERMAL VOLCANICA"],
    "Rutina Completa Caviahue": ["CREMA ANTIAGE NOCHE","CREMA ANTIAGE DIA","SERUM H | Ultra Hydra B5",
                    "AGUA TERMAL VOLCANICA","ESPUMA DE LIMPIEZA FACIAL","CREMA EMOLIENTE PS | 175gr",
                      "CREMA DE MANOS PS","CONTORNO DE OJOS VITAMINA K3"  ],
    "RUTINA CUIDADO FACIAL HOMBRE" :["CREMA FACIAL HOMBRE | 360","AGUA TERMAL VOLCANICA","ESPUMA DE LIMPIEZA FACIAL"],
    "KIT HIDRATACIÓN MINERAL": ["AGUA TERMAL VOLCANICA","BOOSTER MINERAL FACE"],
    "Kit Antioxidante": ["SERUM C+ | Vitamina C","PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW"],
    "Kit Seborregulador": ["SERUM NZ | Niacinamida","ESPUMA DE LIMPIEZA FACIAL"],
    "Kit Ultra Hidratante": ["SERUM H | Ultra Hydra B5","CREMA ANTIAGE DIA"],
    "KIT TERMAL" : ["AGUA TERMAL VOLCANICA","FANGO TERMAL VOLCÁNICO"],
    "Kit Solar Glow": ["PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW","Bruma Facial | Hidratermal"],
    "Kit Doble Limpieza": ["ESPUMA DE LIMPIEZA FACIAL","AGUA MICELAR 400"],
    "Rutina AntiAcne":["GEL DE LIMPIEZA | BALANSIS DERM","CREMA FACIAL | BALANSIS DERM","SERUM GLOW | BALANSIS DERM","FANGO TERMAL VOLCÁNICO"],
    "Rutina Glow":["PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW","SERUM GLOW | BALANSIS DERM","Bruma Facial | Hidratermal","GEL HIDRATANTE | Hidratermal"],
    "Rutina Piel Seca":["MINERAL FACE","AGUA MICELAR 180","CREMA EMOLIENTE PS | 490gr","CREMA ANTIAGE DIA"],
    "Rutina Piel Grasa":["SERUM NZ | Niacinamida","GEL DE LIMPIEZA | BALANSIS DERM","GEL HIDRATANTE | Hidratermal","BRUMA FACIAL | Hidratermal"],
    "Kit Solar": ["AGUA TERMAL VOLCANICA","PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW"],
    "KIT ULTRAHIDRATANTE": [     "CREMA ANTIAGE DIA",        "SERUM H | Ultra Hydra B5"    ],
    "KIT ANTIOXIDANTE": [        "Serum C+ | Vitamina C",        "PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW"   ],
    "KIT SEBORREGULADOR": [        "ESPUMA DE LIMPIEZA FACIAL",        "SERUM NZ | Niacinamida"    ],
    "KIT DOBLE LIMPIEZA": [        "ESPUMA DE LIMPIEZA FACIAL",        "AGUA MICELAR 400"    ],
    "KIT TERMAL": [        "AGUA TERMAL VOLCANICA",        "FANGO TERMAL VOLCANICO"    ],
     "KIT SOLAR GLOW": [        "BOOSTER MINERAL FACE",        "PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW"    ],
     "KIT CALMA Y REPARA": [        "AGUA TERMAL VOLCANICA",        "CICANCALM CREMA"    ],
    "KIT SOLAR": [        "AGUA TERMAL VOLCANICA",        "PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW"    ],
     "RUTINA COMPLETA CAVIAHUE": [        "ESPUMA DE LIMPIEZA FACIAL",        "BOOSTER MINERAL FACE",        "AGUA TERMAL VOLCANICA",
        "FANGO TERMAL VOLCANICO",        "CREMA ANTIAGE DIA",        "CREMA EMOLIENTE CORPORAL PS | 490",        "CONTORNO DE OJOS VITAMINA K3",
        "CREMA DE MANOS PS"    ],
    "RUTINA ANTIAGE": [        "ESPUMA DE LIMPIEZA FACIAL",        "CREMA ANTIAGE DIA",        "SERUM H | Ultra Hydra B5", "CREMA ANTIAGE NOCHE"    ],
    "RUTINA CUIDADO FACIAL HOMBRE": [        "CREMA FACIAL HOMBRE | 360", "ESPUMA DE LIMPIEZA FACIAL",  "AGUA TERMAL VOLCANICA"    ],
    "KIT HIDRATACIÓN MINERAL": [        "AGUA TERMAL VOLCANICA",        "BOOSTER MINERAL FACE"    ],
    "RUTINA GLOW": [        "PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW", "SERUM GLOW | BALANSIS DERM", "Bruma Facial | Hidratermal",      "GEL HIDRATANTE | Hidratermal"    ],
    "RUTINA ULTRALIVIANA": [ "GEL HIDRATANTE | Hidratermal", "PROTECTOR SOLAR FPS 50+ | FACIAL CARE GLOW", "BOOSTER MINERAL FACE", "ESPUMA DE LIMPIEZA FACIAL"    ],
    "RUTINA ANTIEDAD": [        "CREMA ANTIAGE DIA",        "SERUM H | Ultra Hydra B5",        "CREMA ANTIAGE NOCHE"    ],
    "RUTINA ANTIACNE": [        "GEL DE LIMPIEZA | BALANSIS DERM",        "CREMA FACIAL | BALANSIS DERM",        "SERUM GLOW | BALANSIS DERM",        "FANGO TERMAL VOLCANICO"    ],
    "RUTINA PIEL SECA": [        "MINERAL FACE",        "AGUA MICELAR 180",        "CREMA EMOLIENTE PS | 490gr",        "CREMA ANTIAGE DIA"    ]

   
    
   
    



}